#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# request_disc:
#      path: /playlist/request_disc/{numero}
#      controller: App\Controller\PlaylistController::requestDisc
#      options:
#          expose: true